name: Node.js CI functions

on:
  push:
    branches:
      - "main"

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Setup dependencies
        uses: ./.github/actions/steps-deps
      - run: npm ci
        if: steps.node_modules_cache_id.outputs.cache-hit != 'true'

  test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Setup dependencies
        uses: ./.github/actions/steps-deps
      - run: npm run test:ci --if-present

  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Setup dependencies
        uses: ./.github/actions/steps-deps
      - run: npm run build --if-present
